commsOutboundApi:
  uri: srv://comms-outbound-service.service.consul

server:
  context-path: '/quickOtap'
  port: 8080

systemHealth:
    hid: 999
    commsDbInstance: -1
    registrationIntervalSeconds: 120
    heartbeatIntervalSeconds: 60

application:
  name: quickOtap
  displayName: Quick-Otap